### ISSUE TITLE
Bad handle reference lookup leads to panic when lifting

### ISSUE THREAD

**Issue by MrNbaYoh** [fugue-re/fugue-core#6]
The lifter implemented in `fugue` seems to be a port of the buggy C++ Ghidra library, it has several bugs that have been patched in the Java port(?). 
For example, the fugue lifter panics when trying to lift `F5 F7 8C EF`, with the `ARM:LE:32:V8T` language.

When executing `ParserWalker::apply_commits`, it panics at this line:
https://github.com/fugue-re/fugue-core/blob/1ae17934ebfa7b0107c1bfc2ab93bfb753cb0402/fugue-ir/src/disassembly/walker.rs#L380-L385

This happens because when calling `unchecked_handle_ref`, it uses the current `point` and not the `point` where the commit has been added:
https://github.com/fugue-re/fugue-core/blob/1ae17934ebfa7b0107c1bfc2ab93bfb753cb0402/fugue-ir/src/disassembly/walker.rs#L508-L515

In the Java port, they added a `point` member to the `ContextSet` objects to use the proper `point` and get the handle:
https://github.com/NationalSecurityAgency/ghidra/blob/09d326ddbb4294d64e115853e66a4d15f4eed3c0/Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/app/plugin/processors/sleigh/SleighParserContext.java#L127-L135
https://github.com/NationalSecurityAgency/ghidra/blob/09d326ddbb4294d64e115853e66a4d15f4eed3c0/Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/app/plugin/processors/sleigh/SleighParserContext.java#L144-L149

**Comment by xorpse** [comment]
Thank you for the bug report! Can you please check [0a7f77e](https://github.com/fugue-re/fugue-core/commit/0a7f77e6bf4562015f9a0d925b3512cb00d01723) fixes it on your side, please?

**Comment by MrNbaYoh** [comment]
I can confirm 0a7f77e6bf4562015f9a0d925b3512cb00d01723 fixed the bug on my end.
